bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

checkout/urls.py
from django.urls import path
from . import views
from .webhooks import webhook

urlpatterns = [
    path('', views.checkout, name='checkout'),
    path('checkout_success/<order_number>', views.checkout_success,
         name='checkout_success'),
    path('cache_checkout_data/', views.cache_checkout_data,
         name='cache_checkout_data'),
    path('wh/', webhook, name='webhook'),
]

sample_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update total each time a line item is added
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order, null=False, blank=False,
        on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(
        max_length=1, null=True, blank=True)  # S, M, L
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2,
        null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

        def __str__(self):
            return f'Order Number {self.order.order_number}'

checkout/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('full_name', 'email', 'phone_number',
                  'street_address1', 'street_address2',
                  'town_or_city', 'postcode', 'country',
                  'county',)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            'full_name': 'Full Name',
            'email': 'Email Address',
            'phone_number': 'Phone Number',
            'postcode': 'Postal Code',
            'town_or_city': 'Town or City',
            'street_address1': 'Street Address 1',
            'street_address2': 'Street Address 2',
            'county': 'County',
        }

        self.fields['full_name'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if field != 'country':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'stripe-style-input'
            self.fields[field].label = False

checkout/views.py
from django.shortcuts import (render, redirect, reverse,
                              get_object_or_404, HttpResponse)
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.conf import settings

from .forms import OrderForm
from .models import Order, OrderLineItem
from products.models import Product
from profiles.models import UserProfile
from profiles.forms import UserProfileForm
from bag.contexts import bag_contents

import stripe
import json


@require_POST
def cache_checkout_data(request):
    try:
        pid = request.POST.get('client_secret').split('_secret')[0]
        stripe.api_key = settings.STRIPE_SECRET_KEY
        stripe.PaymentIntent.modify(pid, metadata={
            'bag': json.dumps(request.session.get('bag', {})),
            'save_info': request.POST.get('save_info'),
            'username': request.user,
        })
        return HttpResponse(status=200)
    except Exception as e:
        messages.error(request, 'Sorry, your payment cannot be \
            processed right now. Please try again later.')
        return HttpResponse(content=e, status=400)


def checkout(request):
    stripe_public_key = settings.STRIPE_PUBLIC_KEY
    stripe_secret_key = settings.STRIPE_SECRET_KEY

    if request.method == 'POST':
        bag = request.session.get('bag', {})

        form_data = {
            'full_name': request.POST['full_name'],
            'email': request.POST['email'],
            'phone_number': request.POST['phone_number'],
            'country': request.POST['country'],
            'postcode': request.POST['postcode'],
            'town_or_city': request.POST['town_or_city'],
            'street_address1': request.POST['street_address1'],
            'street_address2': request.POST['street_address2'],
            'county': request.POST['county'],
        }
        order_form = OrderForm(form_data)
        if order_form.is_valid():
            order = order_form.save(commit=False)
            pid = request.POST.get('client_secret').split('_secret')[0]
            order.stripe_pid = pid
            order.original_bag = json.dumps(bag)
            order.save()
            for item_id, item_data in bag.items():
                try:
                    product = Product.objects.get(id=item_id)
                    if isinstance(item_data, int):
                        order_line_item = OrderLineItem(
                            order=order,
                            product=product,
                            quantity=item_data,
                        )
                        order_line_item.save()
                    else:
                        for size, quantity in item_data['items_by_size'].items():
                            order_line_item = OrderLineItem(
                                order=order,
                                product=product,
                                quantity=quantity,
                                product_size=size,
                            )
                            order_line_item.save()
                except Product.DoesNotExist:
                    messages.error(request, (
                        "One of the products in your bag wasn't found in our \
                            database. "
                        "Please call us for assistance!")
                    )
                    order.delete()
                    return redirect(reverse('view_bag'))

            request.session['save_info'] = 'save-info' in request.POST
            return redirect(reverse('checkout_success',
                                    args=[order.order_number]))
        else:
            messages.error(request, 'There was an error with your form. \
                Please double check your information.')
    else:
        bag = request.session.get('bag', {})
        if not bag:
            messages.error(request, "There's nothing in your bag at \
                the moment")
            return redirect(reverse('products'))

        current_bag = bag_contents(request)
        total = current_bag['total']
        stripe_total = round(total * 100)
        stripe.api_key = stripe_secret_key
        intent = stripe.PaymentIntent.create(
            amount=stripe_total,
            currency=settings.STRIPE_CURRENCY,
        )

        if request.user.is_authenticated:
            # automatically fill user checkout details
            # form with info provided in user profile
            try:
                profile = UserProfile.objects.get(user=request.user)
                order_form = OrderForm(initial={
                    'full_name': profile.user.get_full_name(),
                    'email': profile.user.email,
                    'phone_number': profile.default_phone_number,
                    'country': profile.default_country,
                    'postcode': profile.default_postcode,
                    'town_or_city': profile.default_town_or_city,
                    'street_address1': profile.default_street_address1,
                    'street_address2': profile.default_street_address2,
                    'county': profile.default_county,
                })
            except UserProfile.DoesNotExist:
                order_form = OrderForm()
        else:
            order_form = OrderForm()

        if not stripe_public_key:
            messages.warning(request, 'Stripe public key is missing. \
                Did you forget to set it in your environment?')

        template = 'checkout/checkout.html'
        context = {
            'order_form': order_form,
            'stripe_public_key': stripe_public_key,
            'client_secret': intent.client_secret,
        }

        return render(request, template, context)


def checkout_success(request, order_number):
    """
    Handle successful checkouts
    """
    save_info = request.session.get('save_info')
    order = get_object_or_404(Order, order_number=order_number)

    if request.user.is_authenticated:
        profile = UserProfile.objects.get(user=request.user)
        # Attach the user's profile to the order
        order.user_profile = profile
        order.save()

        # Save the user's info
        if save_info:
            profile_data = {
                'default_phone_number': order.phone_number,
                'default_country': order.country,
                'default_postcode': order.postcode,
                'default_town_or_city': order.town_or_city,
                'default_street_address1': order.street_address1,
                'default_street_address2': order.street_address2,
                'default_county': order.county,
            }
            user_profile_form = UserProfileForm(profile_data, instance=profile)
            if user_profile_form.is_valid():
                user_profile_form.save()

    messages.success(request, f'Order successfully processed! \
        Your order number is {order_number}. A confirmation \
        email will be sent to {order.email}.')

    if 'bag' in request.session:
        del request.session['bag']

    template = 'checkout/checkout_success.html'
    context = {
        'order': order,
    }

    return render(request, template, context)

checkout/templates/checkout/checkout.html
{% extends "base.html" %}
{% load static %}
{% load bag_tools %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col text-center">
            <h2 class="logo-font mb-2">Checkout</h2>
            <hr class="divider-style w-50 ms-auto me-auto">
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-lg-6 order-lg-last mb-5">
            <p class="text-muted">Order Summary ({{ product_count }})</p>
            <div class="row">
                <div class="col-6 offset-3">
                    <p class="mb-1 mt-0 small text-muted">Item</p>
                </div>
                <div class="col-3 text-right">
                    <p class="mb-1 mt-0 small text-muted">Subtotal</p>
                </div>
            </div>
            {% for item in bag_items %}
            <div class="row mb-3">
                <div class="col-3 mb-1">
                    <a href="{% url 'product_detail' item.product.id %}">
                        {% if item.product.image_front %}
                        <img class="w-100" src="{{ item.product.image_front.url }}" alt="{{ product.name }}">
                        {% else %}
                        <img class="w-100" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                        {% endif %}
                    </a>
                </div>
                <div class="col-6">
                    <p class="my-0"><strong>{{ item.product.name }}</strong></p>
                    <p class="my-0 small">Size:
                        {% if item.product.has_sizes %}{{ item.size|upper }}{% else %}N/A{% endif %}</p>
                    <p class="my-0 small text-muted">Qty: {{ item.quantity }}</p>
                </div>
                <div class="col-3 text-right">
                    <p class="my-0 small text-muted">€{{ item.product.price | calc_subtotal:item.quantity }}</p>
                </div>
            </div>
            {% endfor %}
            <hr class="my-0">
            <div class="row text-right mt-3">
                <div class="col-7 offset-2">
                    <p class="my-0">Order Total:</p>
                </div>
                <div class="col-3">
                    <p class="my-0">€{{ total | floatformat:2 }}</p>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6">
            <p class="text-muted">Please fill out the form below to complete your order</p>
            <form action="{% url 'checkout' %}" method="POST" id="payment-form">
                {% csrf_token %}
                <fieldset class="rounded mb-5">
                    <legend class="fieldset-label small px-2 w-auto">Details</legend>
                    <div class="mb-2">
                        {{ order_form.full_name | as_crispy_field }}
                    </div>
                    <div class="mb-2">
                        {{ order_form.email | as_crispy_field }}
                    </div>
                </fieldset>
                <fieldset class="rounded mb-5">
                    <legend class="fieldset-label small px-2 w-auto">Delivery</legend>
                    <div class="mb-2">
                        {{ order_form.phone_number | as_crispy_field }}
                    </div>
                    <div class="mb-2">
                        {{ order_form.street_address1 | as_crispy_field }}
                    </div>
                    <div class="mb-2">
                        {{ order_form.street_address2 | as_crispy_field }}
                    </div>
                    <div class="mb-2">
                        {{ order_form.town_or_city | as_crispy_field }}
                    </div>
                    <div class="mb-2">
                        {{ order_form.county | as_crispy_field }}
                    </div>
                    <div class="mb-2">
                        {{ order_form.postcode | as_crispy_field }}
                    </div>
                    <div class="mb-2">
                        {{ order_form.country | as_crispy_field }}
                    </div>
                    <div class="form-check form-check-inline float-end">
                        {% if user.is_authenticated %}
                        <label class="form-check-label" for="id-save-info">Save this delivery information to my
                            profile</label>
                        <input class="form-check-input" type="checkbox" id="id-save-info" name="save-info" checked>
                        {% else %}
                        <label class="form-check-label" for="id-save-info">
                            <a class="link-style" href="{% url 'account_signup' %}">Create an account</a> or
                            <a class="link-style" href="{% url 'account_login' %}">login</a> to save this information
                        </label>
                        {% endif %}
                    </div>
                </fieldset>
                <fieldset class="">
                    <legend class="fieldset-label small px-2 w-auto">Payment</legend>
                    <!-- A Stripe card element will go here -->
                    <div class="mb-3" id="card-element"></div>

                    <!-- Used to display form errors -->
                    <div class="mb-3 text-danger" id="card-errors" role="alert"></div>
                    <!-- Pass client secret to the view so we can get the payment intent id -->
                    <input type="hidden" value="{{ client_secret }}" name="client_secret">
                </fieldset>

                <div class="submit-button text-right mt-5 mb-2">
                    <a href="{% url 'view_bag' %}" class="btn button-secondary-style">
                        <span class="icon">
                            <i class="fas fa-chevron-left"></i>
                        </span>
                        <span class="font-weight-bold">Adjust Bag</span>
                    </a>
                    <button id="submit-button" class="btn button-style">
                        <span class="font-weight-bold">Complete Order</span>
                        <span class="icon">
                            <i class="fas fa-lock"></i>
                        </span>
                    </button>
                    <p class="small text-danger my-0 mt-2">
                        <span class="icon">
                            <i class="fas fa-exclamation-circle"></i>
                        </span>
                        <span>Your card will be charged <strong>€{{ total|floatformat:2 }}</strong></span>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="loading-overlay">
    <h1 class="text-light logo-font loading-spinner">
        <span class="icon">
            <i class="fas fa-3x fa-sync-alt fa-spin"></i>
        </span>
    </h1>
</div>
{% endblock %}

{% block postloadjs %}
<script type="text/javascript">
    $("#id_full_name, #id_phone_number, #id_street_address1, #id_town_or_city").attr("pattern", "\\S(.*\\S)?");
</script>
{{ block.super }}
{{ stripe_public_key|json_script:"id_stripe_public_key" }}
{{ client_secret|json_script:"id_client_secret" }}
<script src="{% static 'checkout/js/stripe_elements.js' %}"></script>
{% endblock %}

checkout/templates/checkout/checkout_success.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col text-center">
            <h2 class="logo-font mb-2">Thank You!</h2>
            <hr class="divider-style w-50 ms-auto me-auto toast-display-over">
            <p>Your order information is below. A confirmation email will be sent to {{ order.email }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-lg-10 offset-lg-1">
            <div class="order-confirmation-wrapper p-2 border">
                <div class="row">
                    <div class="col">
                        <span><strong>Order Info:</strong></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-md-4">
                        <p class="mb-0 font-weight-bold">Order Number</p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="mb-0">{{ order.order_number }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-md-4">
                        <p class="mb-0 font-weight-bold">Order Date</p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="mb-0">{{ order.date }}</p>
                    </div>
                </div>

                <div class="row mt-2">
                    <div class="col">
                        <span><strong>Order Details:</strong></span>
                    </div>
                </div>

                {% for item in order.lineitems.all %}
                <div class="row">
                    <div class="col-12 col-md-4">
                        <p class="small mb-0 font-weight-bold">
                            {{ item.product.name }}{% if item.product_size %} - Size
                            {{ item.product_size|upper }}{% endif %}
                        </p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="small mb-0">{{ item.quantity }} @ €{{ item.product.price }} each</p>
                    </div>
                </div>
                {% endfor %}

                <div class="row mt-2">
                    <div class="col">
                        <span><strong>Delivering To:</strong></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-md-4 d-none d-md-block">
                        <p class="mb-0 font-weight-bold">Full Name</p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="mb-0">{{ order.full_name }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-md-4 d-none d-md-block">
                        <p class="mb-0 font-weight-bold">Address 1</p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="mb-0">{{ order.street_address1 }}</p>
                    </div>
                </div>

                {% if order.street_address2 %}
                <div class="row">
                    <div class="col-12 col-md-4 d-none d-md-block">
                        <p class="mb-0 font-weight-bold">Address 2</p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="mb-0">{{ order.street_address2 }}</p>
                    </div>
                </div>
                {% endif %}

                {% if order.county %}
                <div class="row">
                    <div class="col-12 col-md-4 d-none d-md-block">
                        <p class="mb-0 font-weight-bold">County</p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="mb-0">{{ order.county }}</p>
                    </div>
                </div>
                {% endif %}

                <div class="row">
                    <div class="col-12 col-md-4 d-none d-md-block">
                        <p class="mb-0 font-weight-bold">Town or City</p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="mb-0">{{ order.town_or_city }}</p>
                    </div>
                </div>

                {% if order.postcode %}
                <div class="row">
                    <div class="col-12 col-md-4 d-none d-md-block">
                        <p class="mb-0 font-weight-bold">Postal Code</p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="mb-0">{{ order.postcode }}</p>
                    </div>
                </div>
                {% endif %}

                <div class="row">
                    <div class="col-12 col-md-4 d-none d-md-block">
                        <p class="mb-0 font-weight-bold">Country</p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="mb-0">{{ order.country }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-md-4 d-none d-md-block">
                        <p class="mb-0 font-weight-bold">Phone Number</p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="mb-0">{{ order.phone_number }}</p>
                    </div>
                </div>

                <div class="row mt-2">
                    <div class="col">
                        <span><strong>Billing Info:</strong></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-md-4">
                        <p class="mb-0 font-weight-bold">Order Total</p>
                    </div>
                    <div class="col-12 col-md-8 text-md-end">
                        <p class="mb-0">€{{ order.order_total }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12 text-center">
            {% if from_profile %}
            <a href="{% url 'profile' %}" class="btn button-style mb-4">
                <span>
                    <i class="fas fa-chevron-left"></i>
                </span>
                <span>Back to Profile</span>
            </a>
            {% else %}
            <a href="{% url 'products' %}" class="btn button-style mb-4">
                <span>
                    <i class="fas fa-chevron-left"></i>
                </span>
                <span>Keep Shopping</span>
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}